title: PEAPH Puzzle Archive
lang: en
description: An archive of all the puzzles with solutions of past PEA Puzzle Hunt events

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
